//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment1.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft®.
        /// </summary>
        public static string AppLabel1 {
            get {
                return ResourceManager.GetString("AppLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook® Web App.
        /// </summary>
        public static string AppLabel2 {
            get {
                return ResourceManager.GetString("AppLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the light version of Outlook Web App.
        /// </summary>
        public static string CheckBoxString {
            get {
                return ResourceManager.GetString("CheckBoxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and/or password.
        /// </summary>
        public static string LoginFailedString {
            get {
                return ResourceManager.GetString("LoginFailedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in.
        /// </summary>
        public static string LoginOkString {
            get {
                return ResourceManager.GetString("LoginOkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordString {
            get {
                return ResourceManager.GetString("PasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a public or shared computer.
        /// </summary>
        public static string RadioButton1String1 {
            get {
                return ResourceManager.GetString("RadioButton1String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you use Outlook Web App on a public computer. Be sure to sign out when you’ve finished and close all windows to end your session..
        /// </summary>
        public static string RadioButton1String2 {
            get {
                return ResourceManager.GetString("RadioButton1String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a private computer.
        /// </summary>
        public static string RadioButton2String1 {
            get {
                return ResourceManager.GetString("RadioButton2String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you’re the only person who uses this computer. Your server will allow a longer period of inactivity before signing you out..
        /// </summary>
        public static string RadioButton2String2 {
            get {
                return ResourceManager.GetString("RadioButton2String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SigInString {
            get {
                return ResourceManager.GetString("SigInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string TextBlockString1 {
            get {
                return ResourceManager.GetString("TextBlockString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide explanation.
        /// </summary>
        public static string TextBlockString2 {
            get {
                return ResourceManager.GetString("TextBlockString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show explanation.
        /// </summary>
        public static string TextBlockString3 {
            get {
                return ResourceManager.GetString("TextBlockString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Microsoft Exchange.
        /// </summary>
        public static string TextBlockString4 {
            get {
                return ResourceManager.GetString("TextBlockString4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2010 Microsoft Corporation. All rights reserved..
        /// </summary>
        public static string TextBlockString5 {
            get {
                return ResourceManager.GetString("TextBlockString5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address:.
        /// </summary>
        public static string UserNameString {
            get {
                return ResourceManager.GetString("UserNameString", resourceCulture);
            }
        }
    }
}
